/*
 * This file is generated by jOOQ.
 */
package com.test.db;


import com.test.db.tables.MergePerson;
import com.test.db.tables.records.MergePersonRecord;
import com.test.db.udt.records.DressingRecord;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>public.merge_person</code>.
     */
    public static Result<MergePersonRecord> mergePerson(
          Configuration configuration
        , DressingRecord[] arr
    ) {
        return configuration.dsl().selectFrom(com.test.db.tables.MergePerson.MERGE_PERSON.call(
              arr
        )).fetch();
    }

    /**
     * Get <code>public.merge_person</code> as a table.
     */
    public static MergePerson mergePerson(
          DressingRecord[] arr
    ) {
        return com.test.db.tables.MergePerson.MERGE_PERSON.call(
            arr
        );
    }

    /**
     * Get <code>public.merge_person</code> as a table.
     */
    public static MergePerson mergePerson(
          Field<DressingRecord[]> arr
    ) {
        return com.test.db.tables.MergePerson.MERGE_PERSON.call(
            arr
        );
    }
}
