/*
 * This file is generated by jOOQ.
 */
package com.test.db;


import com.test.db.udt.Dressing;


/**
 * Convenience access to all UDTs in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UDTs {

    /**
     * The type <code>public.dressing</code>
     */
    public static final Dressing DRESSING = com.test.db.udt.Dressing.DRESSING;
}
