create table person (
    id bigint primary key generated by default as identity,
    name varchar(50) not null,
    age int not null,
    address jsonb,
    address_vec jsonb,
    address_list jsonb,
    unique(name)
);

create type dressing as (
    id bigint,
    name varchar(50),
    age int,
    address jsonb,
    address_vec jsonb,
    address_list jsonb,
    costume varchar(50)
);

CREATE OR REPLACE FUNCTION merge_person(arr dressing[]) RETURNS SETOF dressing LANGUAGE plpgsql AS
$$
DECLARE x dressing;
BEGIN
    FOREACH x IN ARRAY arr LOOP
        return query insert into person(name, age, address, address_vec, address_list) values (x.name, x.age, x.address, x.address_vec, x.address_list) on conflict (name) do update set age=x.age, address=x.address, address_vec=x.address_vec, address_list=x.address_list returning id,name,age,address,address_vec,address_list,x.costume;
    END LOOP;
    RETURN;
END;
$$;
